package.path = package.path .. ";./script/?.lua;./script/module/redis_test/?.lua"

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/11/6 10:44
---
require("common.dump")
require("common.function")
require("common.trackback")
local log = require("glog")
local gredis = require("gredis")

function main()
    local redis, err = gredis.new("script/module/redis_test/config.json")
    if err ~= nil then
        log.error(err)
        return
    end

    local result, err = redis:set("liwei", "123132")
    if err ~= nil then
        log.error(err)
        return
    end
    log.info({result = result})

    result, err = redis:set("liwei-1", 10000)
    if err ~= nil then
        log.error(err)
        return
    end
    log.info({result = result})

    result, err = redis:set("liwei-2", 10000.123)
    if err ~= nil then
        log.error(err)
        return
    end
    log.info({result = result})


    result, err = redis:set("liwei-3", true)
    if err ~= nil then
        log.error(err)
        return
    end
    log.info({result = result})

    result, err = redis:set("liwei-2", {a=1,b=2})
    if err ~= nil then
        log.error(err)
        return
    end
    log.info({result = result})

    v, err = redis:get("liwei")
    if err ~= nil then
        log.error(err)
        return
    end
    log.info({v = v})

    redis:close()
end

local status, msg = xpcall(main, __G__TRACKBACK__)
if not status then
    print(msg)
end
